# Generated by Django 3.1.1 on 2020-09-09 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping1', models.CharField(max_length=150)),
                ('topping2', models.CharField(max_length=150)),
                ('Burger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burger.size')),
            ],
        ),
    ]
