# Generated by Django 3.1.1 on 2020-09-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='burger',
            old_name='Burger',
            new_name='size',
        ),
    ]
